### ISSUE TITLE
How to run Nerf?)

### ISSUE THREAD

**Issue by Ulugbek98** [city-super/BungeeNeRF#18]
Hey, 
I'm a new comer to NERF world so help me please with running 
here is my Anaconda console output

(bungee) C:\BungeeNeRF>python run_bungee.py --config configs/EXP_CONFIG_FILE
Traceback (most recent call last):
  File "C:\BungeeNeRF\run_bungee.py", line 632, in <module>
    torch.set_default_tensor_type('torch.cuda.FloatTensor')
  File "C:\ProgramData\Anaconda3\envs\bungee\lib\site-packages\torch\__init__.py", line 323, in set_default_tensor_type
    _C._set_default_tensor_type(t)
TypeError: type torch.cuda.FloatTensor not available. Torch not compiled with CUDA enabled.

I've watched intro video on Youtube, and got fantastic inspiration
thank you for great work guys

**Comment by nickhuang-gpu** [comment]
I meet the same error,It could be that your torch version is not compatible, or your torchvision does not match with torch.It requires torch<=1.11.0.I fix it by running: pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113

**Comment by nickhuang-gpu** [comment]
I meet the same error,It could be that your torch version is not compatible, or your torchvision does not match with torch.It requires torch<=1.11.0.I fix it by running: pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
